
name: production-features-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test_schedule:
    runs-on: windows-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.13'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r base_requirements.txt
          python -m pip install jupyter nbconvert nbformat
          python -m pip install hopsworks
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
     
      - name: execute python workflows from notebook
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          
        run: 
          jupyter nbconvert --to notebook --execute 09_production_features_pipeline.ipynb

